# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.8
  - 3.9

before_install:
    - pip install --upgrade pip
    - pip install pipenv
    - pipenv install --dev
install: skip
script:
    - pipenv run make lint
    - pipenv run python setup.py test

{% if cookiecutter.use_pypi_deployment_with_travis == 'y' -%}
# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: {{ cookiecutter.pypi_username }}
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
    python: 3.9
{%- endif %}
