# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
before_install:
    - pip install -U pipenv
    - pipenv install --dev
install: skip
script:
    - nox

# deploy new versions to PyPI
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: stbraun
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: stbraun/python_boilerplate
    python: 3.8
